react-navigation/react-navigation.github.io

docs/custom-android-back-button-handling.md
hi! documenting the android back button behavior. 
In my app, I once also tried to do custom handling of back button while a drawer is open. Unfortunately, my event listeners were not called (react-navigation was swallowing the events) and I had to work around that in a different way, which is why this is not documented.
Let me know if this looks good :)
=> document custom back button behavior

docs/header-buttons.md
So I wrote this package for rendering header buttons that should make people's life easier: https://github.com/vonovak/react-navigation-header-buttons (demo: https://expo.io/@vonovak/navbar-buttons-demo).
This place in the docs is ideal for it to appear, but I'm not sure if it's a good idea to link to some random guy's git repo in the middle of the page (it doesn't seem to be a good precedent to me).
I was thinking we may create a new page with community contributions and collect such packages there? (I have one more that I'd like to share since it may be useful: https://github.com/vonovak/react-navigation-props-mapper).
Alternatively, it may be moved to the react-navigation org and I could maintain it. Then it would be okay to link to it, but again, this cannot be applied to all …
=> document react-navigation-header-buttons

website/static/css/prism-ghcolors.css
Code blocks have a white background-color. In Firefox, selected code was invisible due to `::-moz-selection` styles also declaring a white background.
This PR also removes the commented out `::selection` colors.
=> Fix invisible selection color in code blocks (Firefox)

docs/params.md
similar to https://github.com/react-navigation/react-navigation.github.io/pull/36, I'd like to document the react-navigation-props-mapper package which allows easier access to navigation params through a HOC.
=> document react-navigation-props-mapper

docs/navigation-prop.md
In the event that [#3510 - getParam](https://github.com/react-navigation/react-navigation/pull/3510) gets merged in, this is the documentation to accompany this change.
=> getParam docs

docs/navigation-prop.md
Reverts react-navigation/react-navigation.github.io#52
Should have waited for https://github.com/react-navigation/rfcs/pull/21 first
=> Revert "getParam docs"

docs/tab-based-navigation.md
Line 136 'there' not 'their'.
Line 205 had a typo as &mdahs; which I've corrected, but I've also changed instances of `&dash;` to `&mdash;` where appropriate.
=> Typos and mdashes

docs/custom-navigators.md
Broken `custom-routers` link in `custom-navigation` page
=> fixing broken links

docs/tab-based-navigation.md
Importing of TabBarBottom removed because it is not used in the example
=> Removed unused component importing

docs/stack-navigator.md
This is a documentation update for https://github.com/react-navigation/react-navigation/pull/3496
=> Added safeAreaViewProps documentation

docs/auth-flow.md
Otherwise this.props.navigation will not be available in _bootstrapAsync
=> Add missing props to AuthLoadingScreen

docs/navigating-without-navigation-prop.md, website/sidebars.json
This is one of the things we talked about in slack with @brentvatne. Not sure if `Navigating without the navigation prop` is the best title but here it is.
I have been using this approach to navigating for a while and it has worked well for me, and I made the docs sound like this is a full-featured alternative to the navigation prop since I believe it is true (I hope there are no breaking changes coming :D) and in fact I think it is even better
* you can define your own navigation functions; I use several
* handy if you do not integrate the nav state in redux (as in my case, because I use mobx)
* it gives users an extra abstraction to react-navigation. Eg if it is decided to rename `push` to `navigate` (which happened between ex-navigation and react-navigation [not complaining]), this …
=> document the top-level navigator ref

docs/handling-iphonex.md
There has been some questions how to use `SafeAreaView` and previously it has not been made clear that importing it from `react-navigation` is preferred.
=> Document forceInset prop

docs/navigation-actions.md, docs/stack-actions.md, website/i18n/en.json, website/sidebars.json
Since https://github.com/react-navigation/react-navigation/pull/3619, actions for stack navigators have moved to the `StackActions` object, so the documentation for `replace` and `reset` needed an update. 
For the most part, it's a direct swap of the StackActions content into a new page, with a few additional changes:
* Examples now show `StackActions` being imported and used as well as `NavigationActions`
* Fixed italics on prop types in a few examples
* Added an intro for StackActions and links between the two pages. 
Happy to make additional changes if there's anything missing/unclear. Thanks again for all your work on this project! 
_Note_: I haven't yet added additional docs for `Push`, `Pop` or `PopToTop`.
=> Migrate StackActions to a new page

website/core/Footer.js, website/languages.js, website/pages/en/help.js, website/pages/en/index.js
I did a Chinese translation for React Navigation's official website
There are some changes in two pages(main page and help page).
Modified the source code of the three files(index.js,Footer.js and help.js).
**In index.js**
Translated 3 words, modified 3 hyperlinks
[Link](https://github.com/shixiaoquan/react-navigation.github.io/commit/ca927db7d333fc6abd23a75a0f075e187e7dd1e5#diff-cbcca24c9fdb811cd5d539d933af69fb)
**In Footer.js**
Modified 4 hyperlinks
[Link](https://github.com/shixiaoquan/react-navigation.github.io/commit/5d3ecdced6dc77150f8ed21e3edbd5e24b0e94ad#diff-c16bf3020df7b0cc43221c574b1e75e4)
**In help.js**
Modified 17 hyperlinks
[Link](https://github.com/shixiaoquan/react-navigation.github.io/commit/654dacaa41fc7af3a174d678c07d28847f6927e1#diff-13810425449237fc02a4123dfcea619c)
=> Add Chinese translation for the some pages

docs/custom-navigators.md
There is no property 'route' on a descriptor, but there is a property 'state' that is a shortcut to 'navigation.state'.
=> Fix scene descriptor documentation

docs/community-fluidtransitions.md, website/i18n/en.json, website/sidebars.json
**Motivation**
React Navigation can be extended with custom navigators, and it would be cool to add a section in the documentation about this (idea from: @brentvatne)
**Description**
This pull request contains a new section in the sidebar titled "Community Navigators" and a document with a short introduction about Fluid Transitions. I'm not sure about how complex we want these descriptions to be, but I decided to keep example code out so that we won't need to update the documentation for external projects like this.
**Changes**
- Added section in sidebars.json
- Added community navigator Fluid Transitions
=> Added section about community navigators

docs/navigation-options-resolution.md
Update the quotes around `Welcome` to be consistent so it's valid to copy/paste.
=> Update the quotes in the documentation to be consistent

docs/bottom-tab-navigator.md, docs/material-bottom-tab-navigator.md, docs/material-top-tab-navigator.md, docs/tab-based-navigation.md
Looks like https://github.com/react-navigation/react-navigation.github.io/pull/175 got reverted somehow
=> Updated tab navigator docs

docs/redux-integration.md
Introducing `reduxifyNavigator`, which should make things much simpler.
=> Update Redux Integration docs for react-navigation-redux-helpers@2.0.0

docs/with-navigation.md
The onRef property was added to allow for passing refs to components wrapped by `withNavigation`, as seen in this PR: https://github.com/react-navigation/react-navigation/issues/3461
However, it's not documented. This adds docs.
Corresponding change to typings here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/26714
=> withNavigation docs: add note about the onRef property

docs/stack-actions.md
Updated doc based on [this PR](https://github.com/react-navigation/react-navigation/pull/4636)
Hold merge until 2.7.0 is released
=> Remove required flag from Replace action

docs/navigation-actions.md
In order to avoid confusion the navigation actions methods should be camelCase
=> camelCase navigation actions methods

docs/screen-tracking.md
Fixed wrong method name in redux example of screen-tracking to match the above example!
Changed from: `getCurrentRouteName` to `getActiveRouteName` at L#68 and L#70
=> Updated screen-tracking.md

docs/navigation-options-resolution.md
removed X (or was it there on purpose?)
=> Fix a typo in createNavigator

docs/material-top-tab-navigator.md
Related to https://github.com/react-navigation/react-navigation-tabs/pull/9.
Before merging this, we should release a new version of `react-navigation-tabs`, update it in `react-navigation`, and then release a new version of `react-navigation`.
=> Add lazy and optimizationsEnabled props

docs/material-top-tab-navigator.md
It may sound a bit weird to have a prop `tabBarPosition` on Material *Top* Tab, but it could be useful to use this component as a bottom tab.
=> Add tabBarPosition prop to Material Top Tab

docs/navigation-views.md
Fix not working (404) links on https://reactnavigation.org/docs/en/navigation-views.html
The new links refers to https://github.com/react-navigation/react-navigation-stack
=> Fix links to extracted StackView components

docs/stack-navigator.md
I know it's just a space but it bugged me enough to open a PR. 🐰
=> Add a space to make js formatting consistent in navigation options docs

docs/limitations.md, docs/navigating.md, docs/navigation-options-resolution.md
- I've noticed a redundant curly bracket in one of the code samples (`docs/navigating.md`).
- I changed some `let`s to `const`s to make code samples style consistent (using `const` for variables that don't change).
=> small improvements

docs/bottom-tab-navigator.md, docs/material-bottom-tab-navigator.md, docs/material-top-tab-navigator.md, docs/tab-based-navigation.md, docs/tab-navigator.md
- Closes https://github.com/react-navigation/react-navigation.github.io/issues/241
This documents the `horizontal` prop being passed into `tabBarIcon`.
=> Documents tabBarIcon receiving the `horizontal` prop

docs/drawer-actions.md, docs/navigation-prop.md, docs/stack-actions.md, website/i18n/en.json, website/sidebars.json
some functions were missing from the reference, this should fix it
=> document missing functions on navigation prop

docs/navigation-options-resolution.md, docs/stack-navigator.md
Add entry to the navigation options resolution on how to dynamically set the `mode` property for a stack navigator. This is useful if you have a stack with more than one screen and want to have the `modal` transition on iOS on some screens, but the `card` transition on others.
=> Add resolution to dynamically set the mode for a transition

docs/bottom-tab-navigator.md
While looking up a way to style the createBottomTabNavigator while being exported in React-Native I came across the API Reference page first.  The examples we're a bit confusing before discovering the guides as well.  I think it would be great if some cross linking could be implemented to further help those who may stumble across the API references first before seeing the guides.  Would save a lot of time and further improve some already awesome documentation for React-Navigation.
=> Cross linking back to guides

docs/tab-based-navigation.md
Previously was const TabNavigator createBottomTabNavigator({}) So changed to const TabNavigator = createBottomTabNavigator({
=> Syntax correction

website/versioned_docs/version-1.x/headers.md
Documentation was referring to an unexisting `RouteStack`, when `RootStack` should've been used instead
=> Fix Stack name on v1 documentation

docs/getting-started.md
Now that react-native-gesture-handler needs to be installed manually, the documentation should be complete and specific on how to do this. Seems to have tripped a few people up here: https://github.com/react-navigation/react-navigation/issues/5251
=> add complete installation instructions for Android

docs/getting-started.md, website/versioned_docs/version-3.x/getting-started.md
Please make sure that the edit you're making in `docs/file-you-edited.md` is also included in the file for the correct version, eg. `website/versioned_docs/version-3.x/file-you-edited.md` for version 3. :+1:
=> Add specificity to `react-native link`

docs/stack-navigator.md, website/versioned_docs/version-3.x/stack-navigator.md
Noticed the docs show code samples using `navigationOptions` instead of `defaultNavigationOptions` in config object for `createStackNavigator`.
=> Update code samples in Stack Navigator docs to correctly use defaultNavigationOptions in navigator config

website/versioned_docs/version-3.x/navigating-without-navigation-prop.md
I am trying to follow these two doc pages in conjunction:
- https://reactnavigation.org/docs/en/app-containers.html
- https://reactnavigation.org/docs/en/navigating-without-navigation-prop.html
Though the "Navigating without the navigation prop" seems out of date since the introduction of explicit app containers in v3, the **App Containers** page indicates that I can get a ref on the _container_ that functions just like a navigator. After a couple of false starts, I stumbled upon what seems to be the correct setup, but it would have been helpful to start from a working example without having to infer the correct combination.
My minimal working example:
https://snack.expo.io/@brettdh/navigationservice-and-createappcontainer
Possibly related: react-navigation/react-navigation#5252
> Thanks …
=> Update NavigationService example for v3

docs/navigation-actions.md
this PR is related with https://github.com/react-navigation/react-navigation/issues/5274
=> update NavigationActions reference

docs/action-after-focusing-screen.md, website/versioned_docs/version-3.x/action-after-focusing-screen.md, website/versioned_sidebars/version-3.x-sidebars.json
Adds a guide: **Call an Action After Focusing Screen**
This is in response to this Help Wanted issue: https://github.com/react-navigation/react-navigation.github.io/issues/191
See the guide here: https://deploy-preview-330--react-navigation.netlify.com/docs/en/action-after-focusing-screen.html
=> Adds guide: action on focus

docs/deep-linking.md, website/versioned_docs/version-1.x/deep-linking.md, website/versioned_docs/version-2.x/deep-linking.md, website/versioned_docs/version-3.x/deep-linking.md
This PR adjust deep link set up on Android so the prefix will be the same with iOS.
I also add `android:launchMode` on set up instruction in order to support deep link navigation when the app is running.
=>  Adjust deep link set up and usage on Android

docs/function-after-focusing-screen.md, website/i18n/en.json, website/sidebars.json
this fixes the fact that "Call a function when focused screen changes" is not in the sidebar when you go to the `next` [docs](https://reactnavigation.org/docs/en/next/getting-started.html).
=> fix function-after-focusing-screen.md

docs/connecting-navigation-prop.md
import { withNavigation } from 'react-navigation';
(Suggested) to be removed from first code example to make it more clear to newcomers that it can be used as one approach to receive the navigation prop.
=> import withNavigation removed from button component

docs/routers.md, website/versioned_docs/version-1.x/routers.md, website/versioned_docs/version-2.x/routers.md, website/versioned_docs/version-3.x/routers.md
Hi, this PR fix some broken links to github source code in the routers documentation.
Here is link to test:
https://deploy-preview-359--react-navigation.netlify.com/docs/en/routers.html
https://deploy-preview-359--react-navigation.netlify.com/docs/en/2.x/routers.html
https://deploy-preview-359--react-navigation.netlify.com/docs/en/1.x/routers.html
=> Routers: fix lix to github source code

docs/bottom-tab-navigator.md, docs/material-bottom-tab-navigator.md, docs/material-top-tab-navigator.md, docs/switch-navigator.md, docs/tab-navigator.md, website/versioned_docs/version-3.x/bottom-tab-navigator.md, website/versioned_docs/version-3.x/switch-navigator.md
I've edited the all the docs for new history/order switchrouter backbehaviors in v3/next
@brentvatne I've decided to not document this for Drawer navigator, as I think those behaviors do not make sense it would confuse users.
=> new backbehaviors

docs/tab-based-navigation.md, website/versioned_docs/version-3.x/tab-based-navigation.md
`tab-based-navigation.md` was trying to use `ios-options-outline` from `Ionicons` which doesn't exist. Removed that code so that now the `Settings` icon in the example only uses `ios-options`.
=> Remove nonexistent icon from tab-based-navigation.md

docs/deep-linking.md, website/versioned_docs/version-3.x/deep-linking.md
This PR Fixes #387 by adding documentation to deep linking in nested navigators.
=> Add documentation for deep linking in nested navigators

docs/transitioner.md, website/versioned_docs/version-3.x/transitioner.md
It took a good while for me to find this example searching the web. It would have saved me a lot of searching if the `CustomTransitioner.js` was linked from the official docs. :)
This PR;
- In `transitioner.md`, adds a link to `CustomTransitioner.js` from the `NavigationPlayground` 
- Adds a 3.x versioned `transitioner.md` to the versioned docs folder
=> Link to CustomTransitioner example from NavigationPlayground in Transitioner docs

docs/limitations.md, docs/react-native-screens.md, website/i18n/en.json, website/sidebars.json, website/versioned_docs/version-2.x/limitations.md, website/versioned_docs/version-2.x/react-native-screens.md, website/versioned_docs/version-3.x/limitations.md, website/versioned_docs/version-3.x/react-native-screens.md, website/versioned_sidebars/version-2.x-sidebars.json, website/versioned_sidebars/version-3.x-sidebars.json
add docs sections for `react-native-screens` as in https://github.com/react-navigation/react-navigation.github.io/issues/255
=> add docs for react-native-screens

website/i18n/en.json, website/versioned_docs/version-3.x/screen-tracking.md, website/versioned_sidebars/version-3.x-sidebars.json
*Issue:* [Link to 'Screen Tracking for Analytics' page from 'Deep Linking' page is broken #410](https://github.com/react-navigation/react-navigation.github.io/issues/410)
*Summary:* Small fix for a broken link in the live version of the website.
=> Fix link to 'Screen Tracking for Analytics' page from 'Deep Linking' page.

docs/drawer-based-navigation.md, website/versioned_docs/version-3.x/drawer-based-navigation.md
These guides should always begin with a link to the relevant API documentation
=> Adding link to API documentation

docs/bottom-tab-navigator.md, docs/common-mistakes.md, docs/material-bottom-tab-navigator.md, docs/material-top-tab-navigator.md, docs/scrollables.md, docs/tab-based-navigation.md, docs/themes.md
Maybe we need to create a 4.x alpha and add these docs there? Though if tab and drawer versions are managed independently, not sure how we handle that.
=> Update tab navigator docs to use react-navigation-tabs

docs/state-persistence.md, website/versioned_docs/version-3.x/state-persistence.md
documents https://github.com/react-navigation/native/pull/21
=> document changes to state persistence

docs/stack-navigator.md, website/versioned_docs/version-3.x/stack-navigator.md
=> Update links for files converted to Typescript in stack navigator docs

docs/headers.md
In order to keep consistency on the terminology used across the examples, this component's name should be changed to AppNavigator
=> Change Stack Navigator component's name

docs/getting-started.md, website/versioned_docs/version-3.x/getting-started.md
In the docs, I have added config to disable autolinking on both Android and iOS so that linking is easier with `react-native-link`. Otherwise the user needs to run `git checkout ios` to revert the changes which is another extra step there.
I haven't tested this. Just sent PR because people are having trouble and this is what I found.
cc @thymikee
=> Add docs for linking gesture handler on RN >= 0.60

website/versioned_docs/version-1.x/drawer-based-navigation.md, website/versioned_docs/version-2.x/drawer-based-navigation.md, website/versioned_docs/version-3.x/drawer-based-navigation.md
- Closes #346
- Closes #114
~I updated the examples and snacks to match the version specific usage. I'd been happy to update the links to the snacks to official `/@react-navigation/...` namespaced urls.~ These are now in the `/@react-navigation/...` snacks.
- [`v1`](https://snack.expo.io/@react-navigation/basic-drawer-v1)
- [`v2`](https://snack.expo.io/@react-navigation/basic-drawer-v2)
- [`v3`](https://snack.expo.io/@react-navigation/basic-drawer-v3)
=> Update drawer navigation examples and add snacks

website/versioned_docs/version-4.x/hello-react-navigation.md
```diff
- `createAppContainer` is a function that retuns a React component to take as a parameter
+ `createAppContainer` is a function that returns a React component to take as a parameter
```
URL: https://reactnavigation.org/docs/en/hello-react-navigation.html#creating-a-stack-navigator
=> Fix typo in “Hello React Navigation > Creating a stack navigator” section

docs/tab-based-navigation.md
This doesn't seem to be an issue in other doc versions since they don't use the component-based API.
=> fix docs typo: screenOptopns => screenOptions

website/versioned_docs/version-4.x/tab-based-navigation.md
This only seems to be an issue in v4 of the docs. v3 correctly uses `defaultNavigationOptions` and vNext uses a different API and had a separate issue (#482). Also worth noting that the linked snack correctly has `defaultNavigationOptions`. 
Totally didn't spend half an hour to figure out this was a bug in the docs 😬
=> docs typo: use defaultNavigationOptions tab navigator

docs/navigating-without-navigation-prop.md
In code it is written
```js
export const navigationRef = React.createRef
```
But to create ref, functional call need to be made
```js
export const navigationRef = React.createRef();
```
=> Function call need to be make to create Ref

docs/drawer-based-navigation.md, docs/navigation-context.md
In [`drawer-based-navigation`](https://reactnavigation.org/docs/en/next/drawer-based-navigation.html) it is mentioned to install `react-navigation-drawer` whereas in [`drawer-navigator`](https://reactnavigation.org/docs/en/next/drawer-navigator.html) it is mentioned to install ` @react-navigation/drawer`
I changed the docs to reflect installation mentioned in [`drawer-navigator`](https://reactnavigation.org/docs/en/next/drawer-navigator.html) Page
I also tested drawer navigation by installing `@react-navigation/drawer` and it is working fine
=> Different dependency mentioned in drawer-based-navigation.md

website/versioned_docs/version-3.x/themes.md, website/versioned_docs/version-4.x/themes.md
This is all, just remove the text `(currently in beta)` from iOS 13 references on the themes pages
=> remove ios13 beta status from themes pages (4.x, 3.x)

docs/headers.md
I found that react-navigation 5.x has screenOptions, but not defaultOptions. This PR fixes documentation referencing to defaultOptions.
=> change defaultOptions -> screenOptions

website/pages/en/index.js
Noticed the demo app link on the index page is `404`. I just pointed the url to the new location for the example app. Although I wonder if the user experience could be improved if the button were to just link to the in-browser demo @ https://expo.io/@react-navigation/NavigationPlayground
=> Fix demo app link on index page is 404 - Closes #510

docs/bottom-tab-navigator.md, website/versioned_docs/version-4.x/bottom-tab-navigator.md
Hi,
I noticed that the labelPosition options is missing in the documentation, so I added it :) I am not sure about to which versions I should add it in the documentation. It was released with @react-navigation/tabs 2.3.0, but the versions here in the website repo look like they refer to the versions of the main package. If you give me a hint which versions should be updated, I can update the PR.
Regards
Josef
=> Add documentation for labelPosition option in createBottomTabNavigator

docs/community-libraries-and-navigators.md
Love this little library from @jonsamp and adding it to `Community-developed Navigators and Libraries` after feedback from @satya164 on Twitter: https://twitter.com/satya164/status/1179174667552210944
=> Add react-native-header-scroll-view to Community-developed Navigators and Libraries

docs/deep-linking.md, website/versioned_docs/version-4.x/deep-linking.md
The Deep linking iOS docs indicate to use the long deprecated `appliation:openURL:sourceApplication:annotation:` method. Update to use preferred `application:openURL:options:` method.
=> Fix Deep linking iOS docs using deprecated method

website/versioned_docs/version-4.x/stack-navigator.md
The links under the `Examples` section on this page of the 4.x docs are broken:
https://reactnavigation.org/docs/en/stack-navigator.html
=> Fix broken links in 4.x docs for createStackNavigator API

website/versioned_docs/version-4.x/auth-flow.md
The docs currently say that there isn't a way to animate the transition with a `SwitchNavigator` - this PR updates to refer to `createAnimatedSwitchNavigator`
=> Refer to animated SwitchNavigator in Auth Flow doc

docs/tab-based-navigation.md
Changed the link at the bottom to point to screen-options-resolution rather than navigation-options.
The fix only pertains to next/5.x due to the renaming of navigation-options to screen-options.
=> Fix broken link in tab-based-nav.md

docs/MST-integration.md, docs/alternatives.md, docs/compatibility.md, docs/connecting-navigation-prop.md, docs/navigation-prop.md
to re-link the url to *.md instead of *.html.
to ensure the url in the docs are browse-able.
=> Update some url(s) in the docs from *.html to *.md

website/versioned_docs/version-4.x/stack-navigator.md
The link explaining `TransitionConfig` is broken, so I've updated it to point to the type definitions on the ~~v1.9.4 tag~~ `1.0` branch. Since it's pointing to the ~~tag~~ branch instead of master it shouldn't break again. The transition config is gone in v5 so there's nothing to change in the original file.
=> Fix transitionConfig types link

docs/screen-tracking.md, website/versioned_docs/version-3.x/screen-tracking.md, website/versioned_docs/version-4.x/screen-tracking.md
The repository for `react-native-google-analytics-bridge` has now been archived and users are now recommended to use `@react-native-firebase/analytics`. This commit changes the example to use the more relevant library.
=> update(screen-tracking) change analytics module example

website/blog/2019-11-04-using-react-navigation-5-with-ui-kitten.md
Hi 👋 
We've deprecated an old package in order to use `@ui-kitten/components`. Can we upgrade this guide? I'm going to upgrade [demo app](https://github.com/artyorsh/react-navigation-ex-demo) when it's merged.
=> Update Using with UI Kitten guide

docs/native-stack-navigator.md, website/static/examples/next/native-stack-with-options.js, website/static/examples/next/simple-native-stack.js
Reverted adding NavigationNativeContainer and renamed function name from App to MyStack.
=> revert adding NavigationNativeContainer

website/siteConfig.js
When you want to search something on the docs, this may have same results but for different versions, even if you're looking v4 or next version. This PR should handle this situation, if you're looking at v5 the search results will be only for v5 and the language as well.
=> chore: add filter language and version on search

docs/use-navigation-state.md
I was going through the docs for the useNavigationState hook and realized that the example code contained the wrong signature.
=> fix: correct example code for useNavigationState

website/versioned_docs/version-4.x/themes.md
This PR fixes small issues in themes related examples :
* missing `theme` variable initialization in static context usage example
* missing context initialization in _"Themes inside `navigationOptions`"_
* missing `ThemeContext` import in _"Theming tabs and other similar navigators"_
=> [V4] fix themes related examples

docs/screen-tracking.md
While checking my analytics I noted that my initial screen is not being set.  This has to be done as a separate step which I wanted to clarify.
=> fix: Clarify initial render analytics screen

website/versioned_docs/version-5.x/use-linking.md
Added a short example of `initialRouteName` property usage.
=> feat: add initialRouteName guide to use-linking.md

website/versioned_docs/version-5.x/deep-linking.md
Added guide for handling `initialRouteName` in the nested config for the deep-linking guide.
=> feat: add intialRouteName to deep-linking guide

website/blog/2019-10-17-react-navigation-native.md, website/blog/2019-11-04-using-react-navigation-5-with-ui-kitten.md, website/blog/2020-01-29-using-react-navigation-5-with-react-native-paper.md, website/versioned_docs/version-4.x/limitations.md
Removed /next from links in docs, which broke them.
=> fix: remove /next from links

website/siteConfig.js
currently when we try to edit the docs from the `Edit button` is redirecting to a wrong path.
=> fix: docs edit url

website/versioned_docs/version-5.x/upgrading-from-4.x.md
The v5 migration guide was missing information about NavigationContainer.
=> Add NavigationContainer to upgrading-from-4.x guide

website/versioned_docs/version-4.x/getting-started.md, website/versioned_docs/version-4.x/stack-navigator-1.0.md, website/versioned_docs/version-4.x/stack-navigator.md, website/versioned_docs/version-4.x/troubleshooting.md, website/versioned_docs/version-5.x/navigation-lifecycle.md, website/versioned_docs/version-5.x/navigation-prop.md, website/versioned_docs/version-5.x/nesting-navigators.md, website/versioned_docs/version-5.x/screen-options-resolution.md, website/versioned_docs/version-5.x/upgrading-from-4.x.md
Changed broken links from `.md` to `.html` and added `<NavigationContainer>` where it was needed
=> fix: change .md to.hmtl and add export default to App

website/versioned_docs/version-5.x/react-native-screens.md
`useScreens` is deprecated for v5.x
=> docs: Update react-native-screens.md

website/versioned_docs/version-5.x/use-linking.md
In deep-linking documentation, `ref` is declared with `const ref = React.useRef();`
https://reactnavigation.org/docs/en/deep-linking.html 
But in useLinking doc, it's may lacking
=> docs: useLinking ref is missing

website/static/examples/5.x/tab-based-navigation-minimal.js, website/versioned_docs/version-5.x/params.md
Fixed a typo and changed the example in bottom-tabs to reflect the docs.
=> fix: typo bottom-tabs example

versioned_docs/version-5.x/handling-safe-area.md
Hello. I hope this change is in the right versioned docs folder - it appears to be in `version-5.x`, which is the one I want to edit.
=> docs: spelling and grammar on handling-safe-area

docusaurus.config.js
GitHub link brings me to docusaurus, not react-navigation.
=> docs: fix incorrect github link

versioned_docs/version-5.x/troubleshooting.md
For "Non-serializable values were found in the navigation state" documentation
=> Fix ignoreWarnings code

versioned_docs/version-5.x/material-bottom-tab-navigator.md
There is no `labelStyle` prop so it should not be in the example
=> fix: delete labelStyle from material-bottom-tabs

versioned_docs/version-4.x/getting-started.md, versioned_docs/version-5.x/getting-started.md
Removed instructions to add two lines to the dependencies section in `android/app/build.gradle` as it is no longer required by `react-native-screens` after [this PR](https://github.com/software-mansion/react-native-screens/pull/397).  
`react-native-screens` removed it from their docs [here](https://github.com/software-mansion/react-native-screens/pull/406).
I removed it from v4 and v5 of the docs.  I didn't see it in any of the other versions.
=> docs: remove old react-native-screens instructions

versioned_docs/version-5.x/navigation-prop.md
when we want to reset the routes in v5 we give it a new route not several actions that were in v4
=> fix: Update navigation-prop.md

versioned_docs/version-5.x/getting-started.md
pod-install will ensure the CocoaPods CLI is installed on the device before attempting to run pod install.
=> Use pod-install to minimize distraction

versioned_docs/version-5.x/nesting-navigators.md
**[Example of nested navigators](https://reactnavigation.org/docs/nesting-navigators/) this PR applies to.**
In the [old example](https://reactnavigation.org/docs/nesting-navigators/#navigation-actions-are-handled-by-current-navigator-and-bubble-up-if-couldnt-be-handled), it is said that if `navigate("Settings")` is called from the `Profile` screen, the nested Stack Navigator will handle it. However, there is no nested navigator for the `Profile` screen in the example. Furthermore, it states that if `navigate("Home")` is called from the `Profile` screen, it will bubble up and the parent Tab Navigator will handle it. There is no parent Tab Navigator, however. Therefore, there will be no bubbling up through the navigators. 
The new example reflects what is actually happening with the nested …
=> fix: rewrite nested navigators bubble example

versioned_docs/version-5.x/stack-navigator.md
types.tsx for headerLeft types leads to an archived repository.
Updated the link so that it shows the latest types for headerLeft component
```
```
The change only applies to v5 doc
=> docs: Update link for headerLeft types

versioned_docs/version-5.x/auth-flow.md
The sentence "This can usually be done by checking if we have a token in `AsyncStorage` and validating if token" is a bit confusing. Specifically "validating if token". I believe it's implied that we check if the token exists and validate it.
=> minor typo fix in auth-flow

versioned_docs/version-5.x/configuring-links.md
closes https://github.com/react-navigation/react-navigation.github.io/issues/766
=> Fix typo on configuring-links

versioned_docs/version-5.x/upgrading-from-4.x.md
=> fix: typo in page 'Upgrading from 4.x'

versioned_docs/version-5.x/stack-navigator.md
[According to the source code](https://github.com/react-navigation/react-navigation/blob/0a19e94b23a4d2b5f22d1d9deb0544f586f475ee/packages/stack/src/views/Stack/Card.tsx#L75), this default appears to be `50`
=> fix: Update gestureResponseDistance horizontal default in docs

versioned_docs/version-5.x/hiding-tabbar-in-screens.md
"...the tab bar **is** still stay visible over those..." should read "...the tab bar **will** still stay visible over those..."
=> fix: typo in hiding-tabbar-in-screens

versioned_docs/version-5.x/state-persistence.md
`Platform` was not imported in state-persistence example
I think this only applies to the docs for version 5 — not actually clear what the below is telling me to do; is there another place I should also edit?
=> Missing import in state-persistence example

versioned_docs/version-5.x/deep-linking.md
The example code has an extra parenthesis
=> Remove extra paren from example

versioned_docs/version-5.x/upgrading-from-4.x.md
It should be 'route.params.user' instead of route.params.me in the session The navigation prop ( https://reactnavigation.org/docs/upgrading-from-4.x/ 
Before:
Now:
=> Fix docs for InitialParams

versioned_docs/version-5.x/upgrading-from-4.x.md
rebase of https://github.com/react-navigation/react-navigation.github.io/pull/680
there is no 3.x version of this document, so no versioned doc changes needed here.
=> add import to 5.x example

versioned_docs/version-5.x/header-buttons.md
I've ran into a scene where I'd like to override the onPress of back button without changing its looks.
I've searched and found that you can import `HeaderBackButton` component, but I couldn't find that being mentioned in the document, so I'm adding information for other people who runs into same problem.
=> Add information about HeaderBackButton

versioned_docs/version-5.x/deep-linking.md
I fixed a typo in the code snippet that had an extra closing bracket for better copying and pasting experience.
=> Removed extra bracket from code snippet

versioned_docs/version-5.x/use-scroll-to-top.md
Adds example to `useScrollToTop` docs for using with offset value as discussed in https://github.com/react-navigation/react-navigation/pull/6796 and https://github.com/react-navigation/react-navigation/pull/8637.
=> fix: Adds guide for using offset with useScrollToTop

versioned_docs/version-5.x/custom-navigators.md
The `TabNavigationEventMap` is supposed to be a `Record` of string keys and values which are records with a specific set of keys. Without this change, the event map isn't picked up correctly, and the `data` property is empty. The `defaultPrevented` then also does not exist on the emitted event.
Version: 5.x
I've pressed the "Edit this page" button on the website. Should more files be edited (per the warning)?
=> Fix types in custom navigators doc

versioned_docs/version-5.x/navigating-without-navigation-prop.md
Hi,
thanks for creating and maintaining such a great lib.
I stumbled upon a typo in the docs for V5. The return type for an arrow function within an useEffect should return an object instead of a boolean. This way TypeScript won't complain about a return type other than void.
This is for version 5 of react-navigation only and therefore only changed in the corresponding versioned_docs.
=> docs: changed return type of useEffect()

docusaurus.config.js
Current link is outdated and redirects to 404 page
E.g. https://github.com/react-navigation/react-navigation.github.io/edit/source/versioned_docs/version-5.x/navigation-actions.md
=> docs: Update link to edit docs

versioned_docs/version-5.x/navigation-events.md, versioned_docs/version-5.x/preventing-going-back.md
The label at the top of this doc says v5.x, but it is only available in v5.7+
Reference: https://github.com/react-navigation/react-navigation/pull/8530#issuecomment-658158716
=> docs: Add minimum version to preventing-going-back doc

static/examples/5.x/custom-tab-bar.js, static/examples/5.x/material-top-tab-custom-tab-bar.js, versioned_docs/version-5.x/bottom-tab-navigator.md, versioned_docs/version-5.x/material-top-tab-navigator.md
Changed `accessibilityStates` prop to `accessibilityState`, as `accessibilityStates` prop is no longer being used in react-native
ref: https://github.com/facebook/react-native/pull/26168
```
```
I've looked at version-3.x docs and the changed content did not exist in the older docs.
=> docs: remove deprecated accessibilityStates prop

versioned_docs/version-5.x/community-libraries-and-navigators.md
This small PR removes the link to the deprecated and unmaintained [`react-native-header-scroll-view`](https://github.com/jonsamp/react-native-header-scroll-view) library and the related example link, which also leads to 404.
=> remove deprecated react-native-header-scroll-view

versioned_docs/version-5.x/preventing-going-back.md
In the react-navigation top and bottom tabs, beforeRemove not works, so I described here. Followed https://github.com/react-navigation/react-navigation/issues/8851
=> beforeRemove will not work when tab is unfocused

docusaurus.config.js, src/pages/help.js
The old invite was putting joiners into an error state due to the new Code of Conduct gate! They'd see a "messages failed to load" error, and they'd need to navigate to #welcome first to accept. Not ideal.
=> Update Reactiflux invite URL

versioned_docs/version-4.x/bottom-tab-navigator.md, versioned_docs/version-4.x/drawer-navigator.md, versioned_docs/version-4.x/stack-navigator.md, versioned_docs/version-5.x/bottom-tab-navigator.md, versioned_docs/version-5.x/drawer-navigator.md, versioned_docs/version-5.x/stack-navigator.md
Added information about the new prop to be introduced with 
https://github.com/react-navigation/react-navigation/pull/8805 and https://github.com/react-navigation/react-navigation/pull/8816.
=> Document detachInactiveScreens

versioned_docs/version-5.x/typescript.md
typo is not relevant to previous versions
=> Fixed Typo

versioned_docs/version-5.x/getting-started.md
Now that react-native windows supports react-navigation, I've added a couple of notes in the getting started page due to the fact that react-native-gesture-handler breaks the app on Windows and prevents a successful build.
=> Update getting started to note about Windows

versioned_docs/version-4.x/bottom-tab-navigator.md, versioned_docs/version-4.x/drawer-navigator.md, versioned_docs/version-4.x/hello-react-navigation.md, versioned_docs/version-4.x/material-bottom-tab-navigator.md, versioned_docs/version-4.x/material-top-tab-navigator.md, versioned_docs/version-4.x/navigation-views.md, versioned_docs/version-4.x/routers.md, versioned_docs/version-4.x/stack-navigator.md
The hyperlinks were pointing to the archived `react-navigation` repo so updated them to active repo and that particular branch file.
=> Fix hyperlinks to github react-navigation repo in version 4.x docs

versioned_docs/version-5.x/screen-tracking.md
Thank you all contributors!
I have found a minor typo issue in example code.
wrong: comparision ( including `i` after `s` )
correct: comparison
=> Fix a typo

versioned_docs/version-5.x/params.md
Let's = let us, while here it should be "lets" as in "allows"
=> Fix typo in params section

src/SnackHelpers.js
Hides the query parameters from the URL bar when opening a Snack example. This is made possible by the new `hideQueryParams=true` option https://github.com/expo/snack/blob/main/docs/url-query-parameters.md
**before**
**after**
- Add `'&hideQueryParams=true` to url
=> feat: Hide Snack query params on URL bar

versioned_docs/version-5.x/redux-integration.md
There was an unexpected inline code in `versioned_docs/version-5.x/redux-integration.md`.
=> unexpected inline code syntax removed

versioned_docs/version-3.x/more-resources.md, versioned_docs/version-4.x/more-resources.md, versioned_docs/version-5.x/more-resources.md
Fix link to Harvard Extension School page
=> docs: fix link in More Resources page

versioned_docs/version-5.x/troubleshooting.md
[As of React Native 0.63 YellowBox has been deprecated](https://reactnative.dev/blog/2020/07/06/version-0.63#logbox), i added a note about this in the troubleshooting section and example code.
=> docs: Add note about deprecation of YellowBox

versioned_docs/version-5.x/configuring-links.md
=> fix: linking config example for nested navigators

versioned_docs/version-5.x/navigation-events.md
Grammar updates
This is a simple grammar error spotted in v5.x ( Navigation Events ) documentaion.
Before
After
=> fix: Grammar update in v5.x documentation

versioned_docs/version-5.x/navigation-events.md
This is a fix to a simple grammar error I spotted when reading the documentation.
=> fix: grammar error in latest navigation events documentation

versioned_docs/version-5.x/troubleshooting.md
Removed an unnecessary `>` in `Non-serializable values were found in the navigation >state` 👍 
=> Fix typo in LogBox.ignoreLogs for passing non-serializable values

versioned_docs/version-5.x/getting-started.md
Summary:
Migrated docs from `@react-native-community/masked-view` to `@react-native-masked-view/masked-view`
=> docs: update react-native-masked-view link

versioned_docs/version-5.x/header-buttons.md
this library was previously mentioned in there but was removed with version 5. I believe it is handy to have it mentioned in there, since I think many people will look for something like this.
shameless plug - I'm the author of the lib
=> docs: mention header buttons lib

versioned_docs/version-5.x/screen-options-resolution.md
Remove reference to createTabNavigator() - it's been removed in `react-navigation@3.x`
=> fix: Remove reference to createTabNavigator()

versioned_docs/version-6.x/upgrading-from-5.x.md
In the Markdown file for the document, there is a missing backtick on a section heading.
Previously:
```
`headerMode is moved to options.
```
This PR resolves:
```
`headerMode` is moved to options.
```
---
=> docs: Missing backtick on `headerMode` is moved to options

versioned_docs/version-5.x/screen-tracking.md, versioned_docs/version-6.x/screen-tracking.md
Fixes #1012 (which appears to apply for the v5 and v6 docs).
=> Correct screen tracking call to expo-firebase-analytics API.

versioned_docs/version-6.x/tab-based-navigation.md
The current code snippet uses deprecated option `tabBarOptions` to set `active` and `inactive` tint color properties on a Tab Navigator.
```js
<Tab.Navigator
screenOptions={({ route }) => ({
tabBarIcon: ({ focused, color, size }) => {
let iconName;
if (route.name === 'Home') {
iconName = focused
? 'ios-information-circle'
: 'ios-information-circle-outline';
} else if (route.name === 'Settings') {
iconName = focused ? 'ios-list-box' : 'ios-list';
}
// You can return any component that you like here!
return <Ionicons name={iconName} size={size} color={color} />;
},
})}
tabBarOptions={{
activeTintColor: 'tomato',
inactiveTintColor: 'gray',
}}
>
```
This PR fixes example described under the section: "Customizing the appearance" as:
```js
<Tab.Navigator
screenOptions={({ route }) => ({ …
```
=> docs: fix example snippet for "Customizing the appearance"

src/theme/SearchBar/index.js
Update algolia to search 6.x docs by default as that's now the latest version.
=> Update algolia to search 6.x docs by default

versioned_docs/version-6.x/native-stack-navigator.md
Fix incorrect `searchBar`, `headerSearchBar` prop to correct `headerSearchBarOptions` name in native-stack.
=> fix: incorrect searchBar object name

versioned_docs/version-6.x/upgrading-from-5.x.md
Add missing rename of 
`backButtonImage`->`headerBackImageSource`
`searchBar`->`headerSearchBarOptions` 
to the upgrade guide of native-stack.
=> docs: add missing renamed options in native-stack

versioned_docs/version-6.x/custom-navigators.md
I was getting Typescript errors in my custom navigator following an upgrade from a beta version of v6 to `6.0.2`, so I decided to look into the codebase of React Navigation itself. Seems to me like the docs still require updating here.
See [here](https://github.com/react-navigation/react-navigation/blob/2084fb859ffa7c8ce2de859dba777a1227ff05c2/packages/bottom-tabs/src/navigators/createBottomTabNavigator.tsx#L21) for example in `createBottomTabNavigator`
=> fix(custom-navigators): incorrect typing for Props

versioned_docs/version-6.x/native-stack-navigator.md
Documentation was refering to `createStackNavigator` function instead of `createNativeStackNavigator`
=> fix: renamed createStackNavigator to createNativeStackNavigator

blog/2020-05-16-web-support.md
Fixes #918 
changed `us` to `use`
=> fix: typo(change `us` to `use`)

versioned_docs/version-5.x/stack-navigator.md
The headerLeft option documentation has an invalid link and lists the wrong property names.
=> Fix invalid link in documentation for stack-navigator

versioned_docs/version-6.x/native-stack-navigator.md
an extra ' was placed in headerBlurEffect
=> fixed small typo in Native Stack Navigator

versioned_docs/version-5.x/params.md, versioned_docs/version-6.x/params.md
--- 
Hey there,
I am following along in some of the React Navigation docs, and noticed a grammar error. The `params.md` file of Docs version 5 and 6 were using `an user id` instead of `a user id`. This PR fixes that grammar in both of those files. It was not present in earlier versions. 
Files changed: 
* …
=> Fix grammar in v5 and v6 of params.md

versioned_docs/version-6.x/native-stack-navigator.md, versioned_docs/version-6.x/upgrading-from-5.x.md
Follow up to adding `headerBackButtonMenuEnabled` prop to `@react-navigation/native-stack` in https://github.com/react-navigation/react-navigation/pull/9881
=> feat: add headerBackButtonMenuEnabled prop

versioned_docs/version-6.x/native-stack-navigator.md
This PR adds 3 missing animation types to native-stack documentation - `fade_from_bottom `, `simple_push`, `slide_from_bottom `.
PR connected to https://github.com/react-navigation/react-navigation/pull/9788
=> Add missing animation values to native-stack docs

versioned_docs/version-5.x/tab-actions.md, versioned_docs/version-6.x/tab-actions.md
This pr updates the link text `NavigationActions` to `CommonActions` in `TabActions` to be consistent across other `Action` page. `StackActions` and `DrawerActions` has the same content with `CommonActions` as link text.
=> docs: update link text

static/examples/5.x/drawer-jump-to.js, static/examples/6.x/drawer-jump-to.js, versioned_docs/version-5.x/drawer-navigator.md, versioned_docs/version-6.x/drawer-navigator.md
Added a snack for `jumpTo` to both v5 and v6 docs.
=> Add missing drawer-jump-to example

versioned_docs/version-5.x/use-theme.md, versioned_docs/version-6.x/use-theme.md
Fixed typos in use-theme.md for both v5.x & v6.x docs.
=> Fix spelling `let's us` -> `lets us`

src/pages/home/Splash/index.js, versioned_docs/version-6.x/migration-guides.md, versioned_sidebars/version-6.x-sidebars.json
Update landing page to show migration guide from v5 to v6 by default.
=> docs: update 'coming from' banner

versioned_docs/version-6.x/custom-navigators.md
- fixes issue [#10791](https://github.com/react-navigation/react-navigation/issues/10791)
=> Add missing NavigationContent in the extending navigators section

versioned_docs/version-6.x/typescript.md
In the typescript section;
Adjusted `ProfileScreenNavigationProp` => `ProfileScreenProp`. As `CompositeScreenProps` is used but not `CompositeNavigationProps` in the given example.
=> docs: update/adjust typescript section example

versioned_docs/version-5.x/used-by.md
I extracted the bundle of Coinbase and saw it uses React Navigation. To not have Coinbase in there twice, I replaced Coinbase Pro with the main Coinbase app since it’s way more popular.
=> docs: Coinbase uses React Navigation

versioned_docs/version-6.x/drawer-navigator.md
With this change we will highlight that all 3 steps are required. In old version it looked to me that 3rd step could be only for bare react native project
=> Make drawer installation steps more clear

versioned_docs/version-5.x/typescript.md, versioned_docs/version-6.x/typescript.md
Fixed grammatical errors in `typescript.md` for versions `5.x` and `6.x`.
=> docs(typescript): fix grammar

versioned_docs/version-6.x/tab-based-navigation.md
There is no `ios-list-box` icon in `react-native-vector-icons/Ionicons` icon set. You can check it using https://oblador.github.io/react-native-vector-icons/
That's why using `ios-list` and `ios-list-outline` much more better.
=> Use existing icon in example for Tab Navigation

versioned_docs/version-6.x/drawer-navigator.md
A note about using interpolateNode, instead of interpolate - for reanimated version 2
=> A note about using interpolateNode, instead of interpolate

versioned_docs/version-6.x/navigation-container.md
- Use data instead of notification
[Notification](https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages#notification) does not support `url` property.
- Use optional chaining operators more precisely
- Replace Linking.removeEventListener
`Linking.removeEventListener` is deprecated.
See: https://reactnative.dev/docs/next/linking#removeeventlistener
- Add @react-native-firebase/messaging imports
=> docs: Use message.data instead of message.notification for Firebase Cloud Messaging

versioned_docs/version-6.x/tab-based-navigation.md
When I copied the code from "A native stack navigator for each tab", I realized the header is being duplicated. I checked that in the snack version, there is this "screenOptions" which is missing in the docs. I added it now.
=> Add missing screenOptions to Tab.Navigator

versioned_docs/version-5.x/navigation-state.md, versioned_docs/version-6.x/navigation-state.md
___
Hi there, this change make the docs mention this, in case a developer tries to specify a value for index
apart that is not equal to the last route in a stack and sees that it has no effect, eg. issue #10056.
=> docs: mention index is always last route in a stack

src/pages/help.js
Upon joining I noticed the channel is archived and has been merged into #help-react-native.
I've read the read-me but I don't understand the instructions. So if this pr is wrong feel free to think of it as an issue instead.
=> fix: change channel name for discord

versioned_docs/version-6.x/screen-tracking.md
We used this code on my project, but we had a bug: on some screens, analytics were not sent. 
We used the fix I propose in this PR:`routeNameRef.current` has to be updated **before**  the analytic is sent. If we do it *after*, the user has the time to navigate to a new screen during the time the analytic is sent. But it will be undetected, because previousRouteName would not have been updated already. 
We also can move this line in the "if" block because if they are identical, we don't need to update the reference.
An other solution to achieve the same result is to delete the "await" before Analytics.setCurrentScreen. But I find it more confusing: we "hide" the fact that sending analytics is asynchronous. Especially if some action has to be performed after.
No `screen-tracking.md` file …
=> Code of screen tracking example

versioned_docs/version-6.x/testing.md
The v6 documentation details for mocking are slightly out of date, it's only required to mock react-native-reanimated and react-native-gesture-handler when using certain navigators.
=> docs: update mocking requirements for v6 navigators

static/examples/5.x/screen-tracking-for-analytics.js, static/examples/6.x/screen-tracking-for-analytics.js, versioned_docs/version-5.x/screen-tracking.md, versioned_docs/version-6.x/screen-tracking.md
[expo-firebase-analytics](https://docs.expo.dev/versions/latest/sdk/firebase-analytics/) is getting [deprecated](https://github.com/expo/expo/pull/19398). With SDK 47 going to be released soon, we want developers to migrate from it and use any other mobile analytics SDK.
This PR 
- updates remove references to using `expo-firebase-analytics` from the example in Screen Tracking
- adds a placeholder to indicate at which line the analytics function should be added when using the example
- update the verbiage in context to example
- updates version `6.x` docs and changes backported for `5.x`.
=> docs: update Screen Tracking example to remove expo-firebase-analytics

versioned_docs/version-5.x/headers.md
I've already fixed this typo for the v6 and my changes were accepted. It was still missing for the v5 (only). Now I'm doing it.
Thank you.
=> Typo fix for v5

versioned_docs/version-1.x/tab-navigator.md, versioned_docs/version-2.x/material-top-tab-navigator.md, versioned_docs/version-2.x/tab-navigator.md, versioned_docs/version-3.x/material-top-tab-navigator.md, versioned_docs/version-4.x/material-top-tab-navigator.md, versioned_docs/version-4.x/upgrading-from-3.x.md, versioned_docs/version-5.x/material-top-tab-navigator.md, versioned_docs/version-6.x/material-top-tab-navigator.md
This PR updates all the links for tab-view inside react-navigation docs.
=> chore: update tab-view links

versioned_docs/version-6.x/material-top-tab-navigator.md
This PR adds missing props to material top tabs. 
Including: 
- `tabBarGap`
- `tabBarAndroidRipple`
=> chore: add material top tabs missing props

versioned_docs/version-6.x/custom-navigators.md, versioned_docs/version-7.x/custom-navigators.md
Correctly close the `NavigationContent` tag so that copying the snippet works out of the box for v6 and v7.
=> docs: Add missing closing tag to extending navigators example

versioned_docs/version-6.x/getting-started.md
It seems to have moved from http://reactnativeexpress.com to https://www.reactnative.express
=> fixed link to React Native Express

versioned_docs/version-6.x/native-stack-navigator.md
Added missing `tintColor` option for `headerSearchBarOptions`.
`tintColor`: https://github.com/software-mansion/react-native-screens/blob/main/src/types.tsx#L472
**Example**
`tintColor: "#FF0000"`:
=> docs: add tintColor option for headerSearchBarOptions

versioned_docs/version-6.x/hello-react-navigation.md
Checked all the versioned docs from 1.x to 7.x all the are the same except for this 6.x version.
=> Remove unnecessary texts

versioned_docs/version-6.x/header-buttons.md
This was documented for previous versions of react-navigation. I recently revamped the package so that it can be used in v6 (and probably in v7 as well).
see eg. https://reactnavigation.org/docs/5.x/header-buttons
so I felt like it might be useful to people, thank you
=> docs: mention the header buttons lib

versioned_docs/version-6.x/getting-started.md
updating old React docs links with new ones
=> Updating getting-started.md

versioned_docs/version-6.x/native-stack-navigator.md, versioned_docs/version-6.x/stack-navigator.md, versioned_docs/version-7.x/native-stack-navigator.md, versioned_docs/version-7.x/stack-navigator.md
The code examples for `replace` in both `stack-navigator` and `native-stack-navigator` were using the `push` method instead of `replace`.
=> Fix typo in stack-navigator and native-stack-navigator for `replace` example

versioned_docs/version-6.x/getting-started.md, versioned_docs/version-7.x/getting-started.md
Kotlin is now used in the template starting at 0.73. This PR adds Kotlin examples together with Java.
Currently, Java is opened by default while Kotlin is collapsed, not sure if I should swap, just let me know.
Source: https://github.com/software-mansion/react-native-screens#android
=> chore: add kotlin version of code

versioned_docs/version-6.x/use-is-focused.md, versioned_docs/version-7.x/use-is-focused.md
It re-renders the direct component that contains this hook, but it was mentioned that it re-renders the screen.
=> fixes the re-render warning for using useIsFocused

versioned_docs/version-7.x/state-persistence.md
[AsyncStorage](https://reactnative.dev/docs/asyncstorage) removed from core React-Native, replaced by [react-native-async-storage](https://github.com/react-native-async-storage/async-storage)
=> Migrate 'State persistance' examples to static API

versioned_docs/version-7.x/screen.md
Add static examples - exluding `children` example
=> Migrate 'Screen' examples to static API in v7

versioned_docs/version-7.x/use-focus-effect.md, versioned_docs/version-7.x/use-is-focused.md, versioned_docs/version-7.x/use-navigation-state.md, versioned_docs/version-7.x/use-navigation.md, versioned_docs/version-7.x/use-route.md, versioned_docs/version-7.x/use-scroll-to-top.md, versioned_docs/version-7.x/use-theme.md
Add static examples to hooks from `Hooks` section of `API reference`.
- [useNavigation](https://reactnavigation.org/docs/7.x/use-navigation) - done
- [useRoute](https://reactnavigation.org/docs/7.x/use-route) - done
- [useNavigationState](https://reactnavigation.org/docs/7.x/use-navigation-state) - done
- [useFocusEffect](https://reactnavigation.org/docs/7.x/use-focus-effect) - done
- [useIsFocused](https://reactnavigation.org/docs/7.x/use-is-focused) - done
- [useLinkTo](https://reactnavigation.org/docs/7.x/use-link-to) - nothing to add
- [useLinkProps](https://reactnavigation.org/docs/7.x/use-link-props) - nothing to add
- [useLinkBuilder](https://reactnavigation.org/docs/7.x/use-link-builder) - nothing to add
- [useScrollToTop](https://reactnavigation.org/docs/7.x/use-scroll-to-top) - …
=> Migrate 'Hooks' examples to static API in v7

versioned_docs/version-6.x/deep-linking.md, versioned_docs/version-7.x/deep-linking.md
=> docs: fixed android association documentation link in versioned_docs

versioned_docs/version-6.x/screen-options.md, versioned_docs/version-7.x/screen-options.md
this fixes a possible typo: `to add specify` → `to specify`
I only found this typo in `version-6.x` and `version-7.x` so I updated it only there
=> Fix screen-options.md typo

versioned_docs/version-6.x/limitations.md, versioned_docs/version-7.x/limitations.md
Fixes `react-native-navigation` spelling on the Limitations page (v6 and v7).
=> docs: fix typo in the library name

versioned_docs/version-6.x/deep-linking.md, versioned_docs/version-7.x/deep-linking.md
=> Update 'verifying Android App Links' link

docusaurus.config.js
These are the changes to the [Docusaurus theme config](https://docusaurus.io/docs/api/themes/configuration#color-mode---dark-mode) so that it prefers the user's system color scheme instead of just defaulting to the light one.
I left the light mode as the default for cases when system preferences are unavailable, to be consistent with the official [react.dev](https://react.dev/) documentation ([see this line of code](https://github.com/reactjs/react.dev/blob/main/src/styles/index.css#L384)) and the official React Native documentation (https://github.com/facebook/react-native-website/pull/4262) in this regard.
=> feat: respect user's preferred color scheme

versioned_docs/version-7.x/elements.md, versioned_docs/version-7.x/upgrading-from-6.x.md
I was migrating to React Navigation v7 and I noticed that the docs were a bit outdated. I referred to [this elements changelog](https://github.com/react-navigation/react-navigation/blob/main/packages/elements/CHANGELOG.md#200-rc19-2024-08-05) and [this Native Stack Navigator docs page](https://reactnavigation.org/docs/native-stack-navigator/#headerbackbuttondisplaymode) when making my changes.
I updated the elements docs page itself, and the migration guide to help others with their migrations. Feel free to move it to a different category, as I created a new one for it `"Changes to elements"`.
Please verify my formatting before accepting. I noticed you usually put the default value after the possible values, but I wasn't able to figure out how to do that within the list.
Thanks for the …
=> Replace removed `labelVisible` with `displayMode`.

versioned_docs/version-7.x/material-top-tab-navigator.md
This option was removed in https://github.com/react-navigation/react-navigation/pull/11548
=> remove tabBarIconStyle from material-top-tab-navigator options

versioned_docs/version-7.x/auth-flow.md
I changed "...we're have..." which is the contraction form of "...we are have...". The proposed change is "...we have...", however, please feel free to suggest a different fix.
I read the text generated when I started the PR. I *think* I edited the file it was meaning (i.e. the versioned docs file). Please let me know if I misunderstood and I am happy to correct my error.
=> Fix typo in auth-flow.md

versioned_docs/version-7.x/bottom-tab-navigator.md
The example uses a ternary operator and had a `?` where the `:` should be.
=> Fix syntax error in tabBarPosition example

versioned_docs/version-7.x/custom-navigators.md
In the `TabNavigator` example , `isFocused` Variable is using `index` variable to validate the condition. 
However, the `index` variable is not defined which cause an error of no existing variable.
old example :
```
state.routes.map((route) => ( // missing index
<Pressable
key={route.key}
onPress={() => {
const isFocused = state.index === index; // using undefined variable
...........
}); 
..........
```
=> Update custom-navigators.md : Add missing variable

versioned_docs/version-7.x/native-stack-navigator.md
Changes to docs according to: https://github.com/react-navigation/react-navigation/pull/12500
=> Update docs about headerBackButtonDisplayMode and headerBackTitle

versioned_docs/version-7.x/native-stack-navigator.md
This PR adds deprecation messages to props deprecated in PR https://github.com/react-navigation/react-navigation/pull/12539.
=> docs: add deprecation message to some status/navigation bar related props

versioned_docs/version-7.x/server-rendering.md
Removed extra space in `:::warning` syntax in `versioned_docs/version-7.x/server-rendering.md` to enable proper rendering as a highlighted markdown warning block.
[Before](https://reactnavigation.org/docs/server-rendering)|[After](https://deploy-preview-1423--react-navigation-docs.netlify.app/docs/server-rendering)
-|-
=> Fix `:::warning` syntax in server-rendering docs

versioned_docs/version-7.x/native-stack-navigator.md
Docs changes to: https://github.com/react-navigation/react-navigation/pull/12543
=> Update docs after changes to headerBackTitle

versioned_docs/version-7.x/auth-flow.md
The current [How it will work](https://reactnavigation.org/docs/auth-flow?config=static#how-it-will-work) section is confusing. There is no code snippet in the Static tab. The code snippet which seems like it belongs in the Static tab of the How it will work section is inside of the [Define the hooks](https://reactnavigation.org/docs/auth-flow?config=static#define-the-hooks) section - even though it does not relate to defining hooks. 
There is also a useful general explanation of how it will work which is only visible under the Dynamic tab. I've reorganized things to be more clear.
I've also tried to make the Static and Dynamic code snippets match each other more closely.
The [Define our screens](https://reactnavigation.org/docs/auth-flow?config=static#define-the-hooks) section is …
=> Fix Authentication Flows Static and Dynamic Tab Issues

versioned_docs/version-6.x/native-stack-navigator.md, versioned_docs/version-7.x/native-stack-navigator.md
**Motivation**
Recently noticed that docs for `statusBarStyle` and `statusBarHidden` are not kept in sync between files in `react-native-screens` repo, `react-naviagtion` in-code docs and `reactnavigation.org/docs`.
I added information about `auto` and `inverted` values not being supported on Android for `statusBarStyle`.
Similar PR in `react-native-screens`: https://github.com/software-mansion/react-native-screens/pull/2953, `react-navigation`: https://github.com/react-navigation/react-navigation/pull/12618.
=> docs: add missing status bar docs

.github/PULL_REQUEST_TEMPLATE.md
Use an HTML comment for notational pieces of the PR template
- very similar to an old PR of mine in a different repo: https://github.com/argoproj/argo-helm/pull/1969
- the notes about versioned docs are purely notational, i.e. have nothing to fill out
- comment them out with HTML comments, as is common practice
- example from a repo I maintain: https://github.com/ezolenko/rollup-plugin-typescript2/blob/f6db59613a66f58c48310aa8fa785951970b5d6d/.github/issue_template.md?plain=1#L2
- I copied that from other repos too
- these comments are still visible to the PR author, just not visible when rendered, keeping the PR more concise
Can see an example of what this looks like below vvv. If a maintainer clicks the edit button, will be able to see that the note is still there, just commented out …
=> chore(github): comment out notational pieces of PR template

versioned_docs/version-5.x/contributing.md, versioned_docs/version-6.x/contributing.md, versioned_docs/version-7.x/contributing.md
The Table of Contents (ToC) in the `CONTRIBUTING.md` had duplicated links in v5-v7 docs
- https://github.com/react-navigation/react-navigation.github.io/commit/a986dd6ce828b2c98ccfc12b20ef39c0d8743541 ([this file](https://github.com/react-navigation/react-navigation.github.io/commit/a986dd6ce828b2c98ccfc12b20ef39c0d8743541#diff-63dff0846bfbe2660b99482110780b8d24d4376f99160ddf447ad809b77749ef)) erroneously duplicated links in both sections when one section is "Contributing" and the other is "Information"
- this only affected v5-v7. earlier versions [like v4 are correct](https://github.com/react-navigation/react-navigation.github.io/blob/60212e48ae8b2e85d0d2a63a7f2d824750ebd9c2/versioned_docs/version-4.x/contributing.md?plain=1#L9)
=> fix(contrib): remove duplicated ToC links

versioned_docs/version-7.x/troubleshooting.md
Expanded explanation of the warning regarding non-serializable values in navigation state, including web support.
=> Clarify warning on non-serializable values in navigation
