- website/core/Footer.js
> Point GH link to react-nav repo

- docs/hello-react-navigation.md
- docs/navigating.md
Hello, saw some typos in some pages while reading the docs.
> Fix some typos

- website/siteConfig.js
This adds top-right edit link to the docs, I believe that this is an important thing we're missing since it allows to contribute to the docs very easily.
note it points to the `source` branch, not master
> add edit link

- docs/tab-based-navigation.md
Hi there, thanks for the excellent docs on react-navigation. As I was learning from the code examples I spotted a typo. This pull request will fix it. Keep up the great work.
> Fixed typo in tab-based-navigation code

- docs/headers.md
Status bar is not black, but the status bar text color is.
> [docs] Update headers.md

- docs/contributing.md
- docs/navigation-actions.md
- docs/navigation-options.md
- docs/redux-integration.md
- website/core/Footer.js
The anchors created from the markdown are in lower case. I changed all links to anchors to lower case.
> Fix links to anchors

- docs/getting-started.md
This fixes https://twitter.com/EricVicenti/status/963541803537281024
Unsure you want to keep the content, it's in git still
> fix(getting-started): remove unused code

- docs/navigation-prop.md
see also https://github.com/react-navigation/rfcs/issues/11
> Improve addListener documentation

- website/blog/2018-02-06-react-navigation-1.0.md
> Fix twitter link in the first blog post

- docs/stack-navigator.md
Updated documentation as a consequence of changes in https://github.com/react-navigation/react-navigation/pull/3680
> Updated "headerBackImage" navigation prop description

- docs/drawer-navigator.md
Add activeLabelStyle and inactiveLabelStyle for DrawerItem #3559
https://github.com/react-navigation/react-navigation/pull/3559
> add activeLabelStyle and inactiveLabelStyle to docs

- docs/with-navigation.md
Added missing 'from' for import of Button.
> Fix import statement

- docs/custom-navigators.md
On #141: navigationOptions or `navigationOptions`?
> Typo on #011 ?

- docs/tab-navigator.md
https://github.com/react-navigation/react-navigation/issues/3319
> Remove unsupported configureTransition option

- docs/switch-navigator.md
**Motivation** : I was reading the documentation, and I could not understand the difference between `SwitchNavigator` and `StackNavigator`. I has to look for on StackOverflow and I find [this answer](https://stackoverflow.com/questions/49417757/what-is-the-difference-between-react-navigations-stacknavigator-and-switchnavig). I though it would be a could idea to have it in the documentation.
**Look**:
> Update switch-navigator to explain the use case

- docs/stack-actions.md
In `stack-actions.md` line 99, popAction rather than pushAction should be dispatched
> Dispatch popAction in `stack-actions.md`

- docs/headers.md
update [using-params-in-the-title](https://reactnavigation.org/docs/en/headers.html#using-params-in-the-title) sample code same with [run code](https://snack.expo.io/@react-navigation/using-params-in-title-v2)
> edit using-params-in-the-title document

- docs/redux-integration.md
1. Prefer `createNavigationPropConstructor` to `createReduxBoundAddListener`.
2. Make sure to mention `initializeListeners`.
3. Include `react-navigation-redux-helpers` in `transformIgnorePatterns` for Jest configuration.
4. Miscellaneous language tweaks.
> Update Redux integration docs

- docs/navigating.md
- docs/stack-navigator.md
Related to https://github.com/react-navigation/react-navigation/pull/3540.
> Document initialRouteKey

- docs/community-fluidtransitions.md
> fix typo in community-fluidtransitions.md

- docs/contributing.md
Two small typos in contributing.md
> Fix typos in contributing.md

- docs/stack-navigator.md
> Improved headerBackTitle and headerTruncatedBackTitle docs.

- docs/bottom-tab-navigator.md
Related to the discussion here: https://github.com/react-navigation/react-navigation/issues/4297
> Enhance the doc about tabBarComponent

- docs/stack-actions.md
Updated stack actions to be cameCase
> Updated stack actions to be cameCase

- docs/stack-navigator.md
changing `defualt` > `default`
> Minor typo fix

- docs/redux-integration.md
Please let me know if I'm doing something wrong.
Thanks.
> Fix StackNavigator to createStackNavigator in redux integration doc

- docs/navigation-views.md
> fix 404s in Navigation views docs

- website/static/css/custom.css
fixes
```
createMaterialBottomTabNavigato
r
```
> fix word wrapping

- docs/bottom-tab-navigator.md
- docs/tab-navigator.md
- Closes https://github.com/react-navigation/react-navigation.github.io/issues/197
> Documents the `safeAreaInset` prop for `<TabBarBottom>`

- docs/getting-started.md
> docs(getting-started): Add explanation for hybrid iOS apps

- docs/navigation-prop.md
> fix link to withNavigation doc page

- website/blog/2018-04-06-react-navigation-2.0-rc.md
Updated the link to the custom navigators doc in the blog post.
> Updated Custom Navigators Blog Link

- website/blog/2018-04-06-react-navigation-2.0-rc.md
Updated the blog link to the correct state-persistence doc URL.
> State Persistence Blog Link Updated

- docs/common-mistakes.md
> Miss keyword class

- docs/drawer-based-navigation.md
this PR is related with https://github.com/react-navigation/react-navigation.github.io/issues/233
> add how determine if the drawer is open or closed

- docs/auth-flow.md
- docs/common-mistakes.md
- docs/deep-linking.md
- docs/drawer-based-navigation.md
- docs/drawer-navigator.md
- docs/getting-started.md
- docs/glossary-of-terms.md
- docs/handling-iphonex.md
- docs/header-buttons.md
- docs/headers.md
- docs/hello-react-navigation.md
- docs/limitations.md
- docs/modal.md
- docs/navigating.md
- docs/navigation-options-resolution.md
- docs/params.md
- docs/stack-navigator.md
- docs/status-bar.md
- docs/switch-navigator.md
- docs/tab-based-navigation.md
Changes:
+ Updated all the expo snacks with v3-compatible code and using the latest version of the expo SDK.
+ Added `createAppContainer` in all necessary sample code in the docs where it made sense
+ Updated `navigationOptions` to `defaultNavigationOptions` in all samples/snacks where it made sense
+ Updated install section in getting-started with new dependency
+ Added new features to API pages for v3
+ Added some notes on breaking changes from v2
> Update Snacks/Code Samples for v3

- docs/tab-based-navigation.md
> Fix small syntax mistake

- docs/stack-navigator.md
- website/versioned_docs/version-3.x/tab-based-navigation.md
I merged some minor fixes without noticing we need to check versioned docs too, this fixes what I forgot
> apply fixes across versions

- docs/navigation-options-resolution.md
- website/versioned_docs/version-3.x/navigation-options-resolution.md
closes https://github.com/react-navigation/react-navigation.github.io/issues/298
> use defaultNavigationOptions as appropriate

- docs/handling-iphonex.md
> Fix typo in Landscape Mode

- docs/hello-react-navigation.md
Rootstack isn't mentioned in any of the other code. Causing expo to spit out an error.
> Component name leads to expo throwing error

- docs/deep-linking.md
need two intent filter for it to work. having one intent filter with data removes the launcher icon.
> updated data element

- docs/tab-based-navigation.md
- website/versioned_docs/version-3.x/tab-based-navigation.md
Resolves https://github.com/react-navigation/react-navigation.github.io/issues/81
Snack preview: https://snack.expo.io/@react-navigation/tabs-with-icons-v3
> Add tutorial of adding badges to tabbar icons

- website/versioned_docs/version-2.x/app-containers.md
Added import for createStackNavigator so the example will work.
> Updated Website version for 2.x

- docs/app-containers.md
Added the import of createStackNavigator.
> Upated app-containers.md

- docs/auth-flow.md
- website/versioned_docs/version-1.x/auth-flow.md
- website/versioned_docs/version-2.x/auth-flow.md
- website/versioned_docs/version-3.x/auth-flow.md
* Remove undefined variable in Auth example
> Remove undefined variable in Auth example

- docs/limitations.md
- docs/navigating.md
- website/versioned_docs/version-1.x/connecting-navigation-prop.md
- website/versioned_docs/version-1.x/navigating.md
- website/versioned_docs/version-2.x/connecting-navigation-prop.md
- website/versioned_docs/version-2.x/limitations.md
- website/versioned_docs/version-2.x/navigating.md
- website/versioned_docs/version-3.x/limitations.md
- website/versioned_docs/version-3.x/navigating.md
takes improvements from 
https://github.com/react-navigation/react-navigation.github.io/pull/348/files
https://github.com/react-navigation/react-navigation.github.io/pull/349
https://github.com/react-navigation/react-navigation.github.io/pull/350
and applies them to versioned docs
> improve grammar and other

- docs/drawer-navigator.md
- website/versioned_docs/version-3.x/drawer-navigator.md
Updated v3 docs to include drawerOpenProgress information and example usage.
cc @brentvatne
> Updated v3 docs for drawerOpenProgress

- docs/getting-started.md
> Minor Changes in getting-started.md

- docs/stack-navigator.md
- website/versioned_docs/version-3.x/stack-navigator.md
Here's a link to PR #87 over on react-navigation-stack where the feature was added:
https://github.com/react-navigation/react-navigation-stack/pull/87
> Document new headerBackAllowFontScaling option

- README.md
> Fix typo and tidy up Snack Link in README

- docs/bottom-tab-navigator.md
- website/versioned_docs/version-3.x/bottom-tab-navigator.md
As discussed here: https://github.com/react-navigation/react-navigation/issues/4696#issuecomment-470307427
> document resetOnBlur option for Bottom Tab Navigator

- docs/screen-tracking.md
- website/versioned_docs/version-3.x/screen-tracking.md
See #378 
While I'm editing this page, I believe all the redux content on this page should be removed.
> Update screen tracking page with appContainer

- docs/custom-navigators.md
- website/versioned_docs/version-3.x/custom-navigators.md
Hey, I've discovered the reference to StackRouter wasn't working.
> Fixes reference to StackRouter in custom-navigators.md

- docs/tab-based-navigation.md
description below suggests that this should be `navigationOptions` instead of `defaultNavigationOptions`
> update tab nav example

- docs/navigation-views.md
- website/versioned_docs/version-2.x/navigation-views.md
- website/versioned_docs/version-3.x/navigation-views.md
> Fixed broken link in navigation-views.md

- docs/drawer-navigator.md
- website/versioned_docs/version-3.x/drawer-navigator.md
Add documentation for DrawerLayout prop (https://kmagiera.github.io/react-native-gesture-handler/docs/component-drawer-layout.html) as DrawerNavigationConfig
> Update DrawerNavigationConfig description

- docs/common-mistakes.md
See github issue: https://github.com/react-navigation/react-navigation/issues/5651
> Update common-mistakes.md for wrapping AppContainer in View without flex

- docs/supported-react-native-versions.md
- website/i18n/en.json
- website/sidebars.json
- website/versioned_docs/version-1.x/supported-react-native-versions.md
- website/versioned_docs/version-2.x/supported-react-native-versions.md
- website/versioned_docs/version-3.x/supported-react-native-versions.md
- website/versioned_sidebars/version-1.x-sidebars.json
- website/versioned_sidebars/version-2.x-sidebars.json
- website/versioned_sidebars/version-3.x-sidebars.json
As mentioned in this issue: https://github.com/react-navigation/react-navigation.github.io/issues/335
> add information about supported react-native version

- docs/animated-switch-navigator.md
- website/versioned_docs/version-3.x/animated-switch-navigator.md
the docs in next version and 3.x should be the same in animated switch navigator
> Update source of animated switch navigator

- docs/deep-linking.md
- website/versioned_docs/version-1.x/deep-linking.md
- website/versioned_docs/version-2.x/deep-linking.md
- website/versioned_docs/version-3.x/deep-linking.md
https://github.com/react-navigation/react-navigation.github.io/issues/373
I'm not sure if adding this info to that section is ideal... 🤔
> add section to disable deep-linking

- docs/navigation-context.md
- website/i18n/en.json
- website/sidebars.json
- website/versioned_docs/version-2.x/navigation-context.md
- website/versioned_docs/version-3.x/navigation-context.md
https://github.com/react-navigation/react-navigation.github.io/issues/405
> docs for navigation context

- docs/supported-react-native-versions.md
- website/versioned_docs/version-1.x/supported-react-native-versions.md
- website/versioned_docs/version-2.x/supported-react-native-versions.md
- website/versioned_docs/version-3.x/supported-react-native-versions.md
- Made some updates for grammar and ease of understanding.
- Added a link in each document to file an issue.
> Some improvements to supported RN versions docs.

- docs/bottom-tab-navigator.md
- website/versioned_docs/version-3.x/bottom-tab-navigator.md
referencing: https://github.com/react-navigation/tabs/issues/16#issuecomment-485027123
added to docs/ and v3 docs
> new documentation - tabBarOptions keyboardHidesTabBar

- website/versioned_docs/version-1.x/tab-based-navigation.md
- website/versioned_docs/version-1.x/tab-navigator.md
- website/versioned_docs/version-2.x/bottom-tab-navigator.md
- website/versioned_docs/version-2.x/tab-based-navigation.md
- website/versioned_docs/version-3.x/bottom-tab-navigator.md
- website/versioned_docs/version-3.x/tab-based-navigation.md
> Document tab icon that doesn't navigate

- docs/navigation-prop.md
- website/versioned_docs/version-1.x/navigation-prop.md
- website/versioned_docs/version-2.x/navigation-prop.md
> Provide better documentation with goBack(key)

- docs/navigation-prop.md
- website/versioned_docs/version-2.x/navigation-prop.md
`will` was incorrectly included in a code string, so I fixed that, and in the process I've also updated the formatting of several other code blocks.
> update formatting of Stack Actions

- docs/stack-navigator.md
Adding a bit more details to #454.
Not sure about migration section, probably belongs more to the release docs, but on the other hand I believe that those changes will cause a lot of problems for some people and having it mentioned in the docs would be cool in my opinion.
Also, I am aware that prettier messed up with the samples. I think it is desirable, but let me know if you want to have it removed.
> @tchayen/stack alpha additions

- docs/hello-react-navigation.md
Typo seems to only be in vNext.
> Docs typo: Stck => Stack

- docs/stack-navigator.md
- website/versioned_docs/version-4.x/getting-started.md
if not added this two lines code, the app crashed on android.
Related to this issue https://github.com/react-navigation/react-navigation/issues/6267.
> Added installation of `react-native-screens`

- website/versioned_docs/version-4.x/bottom-tab-navigator.md
If I try to use it like in the document, I get the error "Cannot read property 'map' of undefined".
> tabBarComponent usage error fixed.

- docs/use-is-focused.md
> Fix typo in use-is-focused.md

- docs/tab-based-navigation.md
Fixed couple of old references in the sample code.
> Fix 5.x tab navigation sample code

- docs/typescript.md
https://github.com/react-navigation/navigation-ex/blob/master/packages/bottom-tabs/src/index.tsx#L16
> TabNavigationProp -> BottomTabNavigationProp

- docs/use-is-focused.md
> Fix typo useIsFocused on use-is-focused.md

- docs/glossary-of-terms.md
> Fix typo conponent to component

- docs/themes.md
> Fixed typo

- website/versioned_docs/version-4.x/themes.md
> Fix: Update themes.md

- docs/drawer-navigator.md
> Fix @react-navigation/drawer link

- docs/bottom-tab-navigator.md
> Fix link in bottom-tab-navigator.md

- docs/material-bottom-tab-navigator.md
> Fix link in material-bottom-tab-navigator.md

- docs/material-top-tab-navigator.md
> Fix link in material-top-tab-navigator.md

- docs/hello-react-navigation.md
> Fix link in hello-react-navigation.md

- docs/compatibility.md
> Fix link in compatibility.md

- docs/drawer-based-navigation.md
> Fix link in drawer-based-navigation.md

- docs/headers.md
Some example code provided in this doc file contain error make crash the app on the phone.
> Fix header.md

- docs/community-libraries-and-navigators.md
- docs/compatibility.md
- docs/connecting-navigation-prop.md
- docs/custom-navigators.md
- docs/deep-linking.md
- docs/drawer-navigator.md
- website/versioned_docs/version-1.x/deep-linking.md
- website/versioned_docs/version-2.x/community-libraries-and-navigators.md
- website/versioned_docs/version-2.x/deep-linking.md
- website/versioned_docs/version-3.x/deep-linking.md
- website/versioned_docs/version-3.x/drawer-navigator.md
- website/versioned_docs/version-4.x/deep-linking.md
- website/versioned_docs/version-4.x/drawer-navigator.md
> Fixed typos and errors in documentation

- docs/app-containers.md
- docs/header-buttons.md
- docs/headers.md
- docs/hello-react-navigation.md
- docs/modal.md
- docs/navigating.md
- docs/navigation-lifecycle.md
- docs/params.md
- website/static/examples/next/basic-header-config.js
- website/static/examples/next/custom-header-title-component.js
- website/static/examples/next/full-screen-modal.js
- website/static/examples/next/go-back.js
- website/static/examples/next/header-interaction.js
- website/static/examples/next/header-styles.js
- website/static/examples/next/hello-react-navigation-full.js
- website/static/examples/next/hello-react-navigation.js
- website/static/examples/next/multiple-navigate.js
- website/static/examples/next/multiple-push.js
- website/static/examples/next/multiple-stack-navigator.js
- website/static/examples/next/navigation-lifecycle.js
- website/static/examples/next/new-screen.js
- website/static/examples/next/params-in-title.js
- website/static/examples/next/passing-params.js
- website/static/examples/next/sharing-header-styles.js
- website/static/examples/next/simple-header-button.js
- website/static/examples/next/updating-options-with-setoptions.js
- website/static/examples/next/using-refs.js
- website/static/js/snack.js
- added snacks for most code snippets from guide
- specified deps versions in snack.jsx
> Add snacks for Fundamentals section

- website/blog/2019-11-04-using-react-navigation-5-with-ui-kitten.md
Fixes image links in Using React Navigation 5 with UI Kitten article
> blog: fix using with ui-kitten article links

- docs/hello-react-navigation.md
- docs/navigating.md
- docs/navigation-lifecycle.md
- docs/nesting-navigators.md
- website/static/examples/next/focus-and-blur.js
- website/static/examples/next/hello-react-navigation-with-options.js
- website/static/examples/next/nest-navigators.js
- website/static/examples/next/pop-to-top.js
- website/static/examples/next/use-focus-effect.js
Added missing snacks for examples in Fundamentals docs.
> [Docs]: update snacks in Fundamentals

- docs/tab-based-navigation.md
https://reactnavigation.org/docs/en/tab-based-navigation.html#add-badges-to-icons
Hee's the snack as well: https://snack.expo.io/rJOD3FT6H
> Fixed icons in example 'Tab navigation' - Add badges to icons

- docs/tab-based-navigation.md
Reverts react-navigation/react-navigation.github.io#585
> Revert "Fixed icons in example 'Tab navigation' - Add badges to icons"

- website/static/examples/next/safe-area-example.js
Moved SafeAreaView import from 'react-native-safe-area-view' to 'react-native-safe-area-context'
> fix safe-area-example.js

- docs/drawer-based-navigation.md
> typo "site" corrected to "side"

- docs/native-stack-navigator.md
- website/static/examples/next/native-stack-with-options.js
- website/static/examples/next/simple-native-stack.js
Fixed missing NavigationNativeContainer in examples and added snacks to them
> Update native stack navigator guide

- docs/typescript.md
> Consistency in variable naming

- docs/material-top-tab-navigator.md
Added note to labelStyle concerning activeTintColor and inactiveTintColor. See #576
> Add note to labelStyle

- docs/common-mistakes.md
- docs/troubleshooting.md
- website/i18n/en.json
- website/sidebars.json
Added troubleshooting section to solve common problems which occur while using React Navigation.
> add first look on troubleshooting section

- website/static/examples/4.x/auth-flow.js
- website/versioned_docs/version-4.x/auth-flow.md
I've created the `auth-flow.js` on example/4.x and replaced the snack link to in-line snack
> update docs for auth flow usage 4.x

- website/siteConfig.js
- website/static/css/code-block-buttons.css
- website/static/js/code-block-buttons.js
I added the "copy" code button for every code on our docs
> chore: add copy code button

- docs/screen-tracking.md
Fix an error on React Navigation V5 docs
> Add navigationRef

- docs/use-navigation-state.md
- website/static/examples/next/use-navigation-state.js
Added snack to useNavigationState and fixed typo.
> feat: add snack to use-navigation-state

- website/versioned_docs/version-2.x/deep-linking.md
- website/versioned_docs/version-3.x/deep-linking.md
- website/versioned_docs/version-4.x/deep-linking.md
Added guide for deep linking concerned in #476.
> add 'manually handling deep linking' guide

- docs/native-stack-navigator.md
Update options:
- `presentation` => `stackPresentation`
- `animation` => `stackAnimation`
> Fix docs about stackAnimation and stackPresentation options

- website/versioned_docs/version-5.x/upgrading-from-4.x.md
> fix broken link

- website/blog/2020-02-06-react-navigation-5.0.md
Thanks for the great writeup! So hyped about react-navigation 5!
This PR only contains changes to the blog, and not to documentation.
> Fixing small typo on blog post from 2020-02-06

- website/versioned_docs/version-5.x/stack-navigator.md
Small change in example code. Lost paranthesis
> Update transparent modal example

- website/versioned_docs/version-5.x/drawer-navigator.md
Should default to true on both platforms
> fix: change default gestureEnabled to true

- website/versioned_docs/version-5.x/deep-linking.md
> race needs an array

- package.json
- yarn.lock
the 404-page link was fixed on docusaurus alpha.43
> Fix 404 route

- src/theme/SearchBar/algolia.css
- src/theme/SearchBar/index.js
- src/theme/SearchBar/styles.css
I just created a custom SearchBar component following the same code as the current, but for all search results instead of handling in an SPA will redirect the page.
> fix: redirect algolia search results

- static/examples/5.x/system-themes.js
- versioned_docs/version-5.x/tab-based-navigation.md
- versioned_docs/version-5.x/themes.md
Fixed one link and added snack link for an example
> fix: links and snack

- docusaurus.config.js
closes https://github.com/react-navigation/react-navigation.github.io/issues/706
> fix: footer links

- versioned_docs/version-4.x/community-libraries-and-navigators.md
- versioned_docs/version-5.x/community-libraries-and-navigators.md
closes https://github.com/react-navigation/react-navigation.github.io/issues/537
> fix: move react-native-header-scroll-view community package to v4

- versioned_docs/version-5.x/auth-flow.md
fixes typo in react-navigation v 5.x authentication flows
> fix: typo in v5 auth flows

- versioned_docs/version-5.x/deep-linking.md
Added a guide for deep linking with an example app.
> feat: add guide to newer docs

- versioned_docs/version-5.x/compatibility.md
> The upgrade guide url takes you to a 404 page. :)

- versioned_docs/version-5.x/route-prop.md
> The current route name is `route.name`

- versioned_docs/version-5.x/hello-react-navigation.md
- versioned_docs/version-5.x/params.md
> docs: fix typo in hello-navigation page

- src/pages/index.js
react-navigation 5 is really cool! 😎 so it will be cool if when users open our website they can see the migration guide easily.
> chore: add announcement migration v4 to v5 on Home page

- versioned_docs/version-5.x/drawer-navigator.md
The property name is actually swipeEnabled
> fix: small change in drawer-navigator.md

- versioned_docs/version-5.x/hiding-tabbar-in-screens.md
> docs: spellcheck "firs" -> "first"

- versioned_docs/version-5.x/compatibility.md
Added @ react-navigation/stack package in the compatibility documentation.
> docs: added @ react-navigation/stack package - compatibility v4 -> v5

- versioned_docs/version-5.x/stack-navigator.md
I had to browse through multiple source files to find out this information. Hopefully this saves someone a couple hours in the future.
References: https://github.com/react-navigation/react-navigation/blob/3df65e28197db3bb8371059146546d57661c5ba3/packages/stack/src/views/Stack/CardStack.tsx#L468
> Add note regarding Stack transition config

- versioned_docs/version-5.x/glossary-of-terms.md
Added the term "Navigator" to the glossary of terms.
> feat: Update glossary-of-terms.md

- versioned_docs/version-5.x/header-buttons.md
Added active link to a broken link of headerBackImage.
> feat: Fixed issue #744.

- versioned_docs/version-5.x/header-buttons.md
API reference of headerLeft wasn't present in any of the documentation, so I replaced that broken link with an exmaple so that it will be easier to understand.
> feat: Resolved second link of issue #744.

- versioned_docs/version-5.x/configuring-links.md
This example doesn't make sense unless this is here
> Fix deep linking config example

- versioned_docs/version-5.x/screen-options.md
I think this is only relevant for the v5 docs.
> docs: fix broken link

- versioned_docs/version-5.x/deep-linking.md
As discussed in https://github.com/react-navigation/react-navigation/pull/8252
> Add section about Universal Links

- blog/2019-11-04-using-react-navigation-5-with-ui-kitten.md
Update "Using with UI Kitten" guide, since we published new version recently 🙌 
> Make sure to add your changes to versioned docs
Looks like it's not required, since this guide is focused on v5.
> chore: update using with ui-kitten guide

- versioned_docs/version-5.x/state-persistence.md
closes https://github.com/react-navigation/react-navigation.github.io/issues/778
> Fix state variable on state-persistence

- versioned_docs/version-5.x/themes.md
> Providing a theme will take care of styling all of the official navigators you.
- ... official navigators. [This PR]
- ... official navigators you'd use.
- ... official navigators you'd use within the NavigationContainer.
> fix: typo in themes

- versioned_docs/version-5.x/getting-started.md
Add @react-native-community/masked-view to the description of the libraries you'll install.
> Add to library list

- versioned_docs/version-5.x/drawer-navigator.md
> docs: Update drawer-navigator.md

- versioned_docs/version-5.x/used-by.md
Add CuppaZee to the "Used By" list
> Add CuppaZee

- versioned_docs/version-5.x/used-by.md
Add `Prep - University Companion` to the "Used By"
> docs: 📺  Add Prep - University Companion to Used By

- versioned_docs/version-5.x/used-by.md
Add `Rocket.Chat` to "Used by"
> Add Rocket.Chat to used by

- versioned_docs/version-5.x/themes.md
Add `notification` to Theme docs. Related to https://github.com/react-navigation/react-navigation/commit/96c7b688ce773b3dd1f1cf7775367cd7080c94a2
Not sure how to make semantic pass :|
> feat: add notification do Theme docs

- package.json
- src/pages/index.js
- src/theme/SearchBar/index.js
- yarn.lock
Reverts react-navigation/react-navigation.github.io#834
> Revert "bump docusaurus"

- versioned_docs/version-5.x/used-by.md
Add NMF.earth to the "Used By" list
> Add NMF.earth

- versioned_docs/version-5.x/typescript.md
Just making this part a bit more readable.
> Update typescript.md line 29. A vs An & exempli gratia for more readable example.

- versioned_docs/version-5.x/bottom-tab-navigator.md
> docs: Minor typo fix in bottom-tab-navigator

- versioned_docs/version-5.x/params.md
const { itemId } = route.params;
const { otherParam } = route.params;
can be combine into {itemId, otherParam}
> {itemId, otherParam}

- versioned_docs/version-5.x/deep-linking.md
related: (https://github.com/react-navigation/react-navigation/pull/8942)
> docs: wildcard support

- versioned_docs/version-5.x/use-scroll-to-top.md
'Providing scroll offset' example was wrong.
> docs: Update use-scroll-to-top.md

- versioned_docs/version-5.x/bottom-tab-navigator.md
- versioned_docs/version-5.x/material-top-tab-navigator.md
This PR goes in conjunction with https://github.com/react-navigation/react-navigation/pull/8947
> feat: add sceneContainerStyle description for bottom-tabs navigator

- versioned_docs/version-5.x/nesting-navigators.md
> docs: Fix a typo

- versioned_docs/version-5.x/navigation-prop.md
Added comments to the doc about proper setOption/setParams usage
> Comments from #8621 about calling setOption/setParams after mount

- versioned_docs/version-5.x/redux-integration.md
This fixes a small typo with a code example.
> Fix a typo with a code example

- LICENSE
- README.md
Create LICENSE
> ℹ️  What types of changes does your code introduce?
> 👉 _Put an `x` in the boxes that apply_
> fix: create LICENSE

- versioned_docs/version-5.x/troubleshooting.md
> Fix small typo

- versioned_docs/version-5.x/material-bottom-tab-navigator.md
> fix: Update prop in tab navigator example

- versioned_docs/version-5.x/redux-integration.md
I've changed it to match the name on line 38.
> fix name of variable reference

- versioned_docs/version-5.x/getting-started.md
Reverts react-navigation/react-navigation.github.io#940
> Revert "docs: update react-native-masked-view link"

- versioned_docs/version-5.x/use-link-to.md
> Use correct component name in useLintTo usage example

- versioned_docs/version-5.x/testing.md
Fix Jest the warning: Animated: `useNativeDriver` for react-native@0.64.x.
> docs: fix the jest warning: Animated: `useNativeDriver`

- versioned_docs/version-5.x/used-by.md
- versioned_docs/version-6.x/used-by.md
> Adding Disprz to used-by.md

- versioned_docs/version-4.x/themes.md
Minor fix: `ThemeConext` => `ThemeContext`
> docs: update themes doc

- docusaurus.config.js
> Fix typo in docusaurus.config.js

- versioned_docs/version-5.x/configuring-links.md
- versioned_docs/version-6.x/configuring-links.md
Fixes: #895 
Changelog:
- Removed incomplete sentence
> fix(incomplete-sentence): remove incomplete sentence

- versioned_docs/version-6.x/used-by.md
Adds Surely Todos as an example of an app using React Navigation
> docs: add Surely to Used By

- versioned_docs/version-5.x/auth-flow.md
- versioned_docs/version-6.x/auth-flow.md
Fix issue #1095 
Only involves docs.
> docs: `IsSigned` in instead of `IsSignedIn` in auth-flow page

- versioned_docs/version-6.x/native-stack-navigator.md
> [Docs] Fix typo in code example in native-stack-navigator.md

- docusaurus.config.js
Added the banner as done in the [react-native documentation](https://github.com/facebook/react-native-website/commit/af1484b1f0ed551e7e2d02595dce66bd404c4023#diff-bc4913d026ae51bef2bc8b7a1c040fdf52b999d99e6fa40d87b379f98a60e0eaR158).
> feat: Adding Ukrain aid banner

- versioned_docs/version-6.x/deep-linking.md
correcting "implmenting" spelling to "implementing"
> mistype ( spelling ) correction

- versioned_docs/version-5.x/params.md
- versioned_docs/version-6.x/params.md
Tiny grammatical error, updated "this can leads" to "this can lead". Hope everyone has a great day.
> docs: small grammar fix. This can leads -> this can lead

- versioned_docs/version-6.x/typescript.md
> Fixed missing ` to correct code snippet

- versioned_docs/version-6.x/native-stack-navigator.md
Adds documentation for new props.
Requested by @brentvatne [here](https://github.com/react-navigation/react-navigation/pull/10578#issuecomment-1130464654)
Should be merged with [this PR](https://github.com/react-navigation/react-navigation/pull/10578#issuecomment-1130464654)
> feat: add new props for native-stack

- versioned_docs/version-6.x/upgrading-from-5.x.md
> Remove unnecessary double `the`

- versioned_docs/version-6.x/status-bar.md
Looking at other places in the docs, I realized that this code snippet have a wrong import
> fix: fix SafeArea imports

- versioned_docs/version-6.x/custom-android-back-button-handling.md
- versioned_docs/version-6.x/navigation-container.md
- Docs: https://reactnative.dev/docs/appstate#removeeventlistener
> Don't use deprecated method `removeEventListener()`

- versioned_docs/version-5.x/more-resources.md
See https://github.com/react-navigation/react-navigation.github.io/pull/907
Sorry for being late with this. Having my first newborn at home, things take some more time at the moment 😅
> docs: update more resources docs

- versioned_docs/version-5.x/use-focus-effect.md
Added explanation of what the cleanup function is and how the user creates it.
> docs: Update use-focus-effect.md to explain cleanup function

- versioned_docs/version-5.x/drawer-navigator.md
[react-navigation#9397](https://github.com/react-navigation/react-navigation/issues/9397)
> docs: statusBarAnimation prop only works on iOS

- versioned_docs/version-6.x/native-stack-navigator.md
Simple change to the headerSearchBarOptions example.
> fix: headerSearchBarOptions documentation

- versioned_docs/version-6.x/material-top-tab-navigator.md
Need to `pod install` after installing `react-native-pager-view`
> Missing `pod install` step for installation

- versioned_docs/version-5.x/screen-options.md
> fix typo in screen-options.md

- yarn.lock
This PR combines all dependabot PRs into one.
> Update Dependabot dependencies

- versioned_docs/version-7.x/themes.md
* Important change from `react-native-appearance' to 'Appearance' from React Native (functionality was added to the core)
> Migrate 'Themes' examples to v7

- versioned_docs/version-7.x/screen-tracking.md
Needs adjustment for when the ref is fixed.
> Migrate 'Screen tracking for analytics' examples to static API

- blog/2024-06-27-react-navigation-7.0-rc.md
Command for trying v7 is breaking due to a typo :)
> Fix typo on try it out section

- versioned_docs/version-6.x/getting-started.md
Before: `NavigationContainer`s
After: `NavigationContainers`
> Typo Fixed.

- versioned_docs/version-7.x/upgrading-from-6.x.md
When reading the V7 upgrade guide, what appears to be an accidently added word caused me some confusion.
> Update upgrading-from-6.x.md (minor typo)

- versioned_docs/version-6.x/handling-safe-area.md
Changed 'Analitics' to 'Analytics'
> Fix Typo - handling-safe-area.md

- versioned_docs/version-6.x/getting-started.md
Reverts react-navigation/react-navigation.github.io#1295
> Revert "Typo Fixed."

- static/examples/5.x/stack-actions.js
- static/examples/6.x/stack-actions.js
- versioned_docs/version-7.x/stack-actions.md
related to: [Update stack-actions.js](https://github.com/react-navigation/react-navigation.github.io/pull/1239)
> docs: Fixed swapped button titles

- versioned_docs/version-7.x/configuring-links.md
> Fix typo in `configuring-links.md`

- versioned_docs/version-6.x/navigation-solutions-and-community-libraries.md
- versioned_docs/version-7.x/navigation-solutions-and-community-libraries.md
This PR mentions `react-native-bottom-tabs` in Community Libraries section.
> docs: add react-native-bottom-tabs

- blog/2018-04-06-react-navigation-2.0-rc.md
- docusaurus.config.js
- package.json
- yarn.lock
> Docusaurus 3.6.1

- versioned_docs/version-7.x/auth-flow.md
- Removed duplicat code from versioned_docs/version-7.x/auth-flow.md
> docs: Removed duplicate code from auth-flow example
